-- Run this in the Supabase SQL editor to create the projects table.

create table public.projects (
  id bigint generated by default as identity primary key,
  newrep text not null default '',
  month text not null default '',
  channel text not null default '',
  delivery text not null default '',
  startup text not null default '',
  bm text not null default '',
  complexity text not null default '',
  model_desc text not null default '',
  sold_by text not null default '',
  alloc_j numeric not null default 0,
  alloc_m numeric not null default 0,
  alloc_n numeric not null default 0,
  alloc_a numeric not null default 0,
  alloc_g numeric not null default 0,
  alloc_s numeric not null default 0,
  description text not null default '',
  upwork_name text not null default '',
  country text not null default '',
  contact text not null default '',
  email text not null default '',
  date text not null default '',
  amount numeric not null default 0,
  billing_thru text not null default '',
  invoicing_value text not null default '',
  booked_amount_status text not null default '',
  ready_for_billing boolean not null default false,
  notes text not null default '',
  invoices jsonb not null default '[]'::jsonb
);

-- The app talks to Supabase directly from the browser using the anon key,
-- so RLS must be enabled with a policy that allows that access.
-- This app has no auth, so this policy allows anyone with the anon key
-- (i.e. anyone who can load the app) to read/write all rows.
alter table public.projects enable row level security;

create policy "Allow anon full access"
  on public.projects
  for all
  to anon
  using (true)
  with check (true);
